
//register admin user
export const TEACHER_REGISTER="TEACHER_REGISTER"
export const SIGNIN_SUCCESFULL="SIGNIN_SUCCESFULL"
export const SIGNIN_FAILD="SIGNIN_FAILD"
export const USER_SIGNIN="USER_SIGNIN"
export const FEATCH_USER_DETSILS="FEATCH_USER_DETSILS"
export const ADD_STUDENT = "ADD_STUDENT"
export const FEATCH_STUDENT = "FEATCH_STUDENT"
export const USER_LOGOUT = "USER_LOGOUT"
export const REMOVE_STUDENT = "REMOVE_STUDENT"
export const EDIT_STUDENT = "EDIT_STUDENT"
export const FEATCH_STUDENT_DETSIL = "FEATCH_STUDENT_DETSIL"


